version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  
jobs:

  test_and_lint:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: create venv
          command: make setup
      - run:
          name: install
          command: |
            make install
            wget https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
            chmod +x hadolint-Linux-x86_64
            ./hadolint-Linux-x86_64 Dockerfile
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test


  install-dependencies:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          name: create venv
          command: make setup
      - run:
          name: install
          command: |
            make install
            cd venv
            ls 
      - save_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  lint-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test

  build-image:
    docker:
      - image: cimg/aws:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: 
          name: build-and-push
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> ${BASH_ENV}
            echo 'export IMAGE_NAME=${CIRCLE_PROJECT_REPONAME}' >> ${BASH_ENV}
            source ${BASH_ENV}
            docker build --tag ${IMAGE_NAME}:${TAG} .
            docker images

            # TAG=0.1.$CIRCLE_BUILD_NUM
            # docker build --tag dockey-python:$TAG .
            # docker images
            # aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 251367170217.dkr.ecr.us-east-1.amazonaws.com
            # docker tag dockey-python:$TAG 251367170217.dkr.ecr.us-east-1.amazonaws.com/udacity:$TAG
            # docker push 251367170217.dkr.ecr.us-east-1.amazonaws.com/udacity:$TAG
            
          

workflows:
  build-and-lint:
    jobs:
      - test_and_lint
      - build-image:
          requires:
            - test_and_lint
      - aws-ecr/build_and_push_image:
          region: us-east-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - build-image            