version: 2.1

jobs:

  test_and_lint:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: create venv
          command: make setup
      - run:
          name: install
          command: |
            make install
            ls
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test


  install-dependencies:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          name: create venv
          command: make setup
      - run:
          name: install
          command: |
            make install
            cd venv
            ls 
      - save_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  lint-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test

  build-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: install make
          command: |
            wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
            tar xf cmake-3.2.2.tar.gz
            cd cmake-3.2.2
            ./configure
      - run:
          name: build-image
          command: make build_image
  
workflows:
  build-and-lint:
    jobs:
      - test_and_lint
      - build-image:
          requires:
            - test_and_lint