version: 2.1


jobs:
  build-and-lint:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: install
          command: make install
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test

workflows:
  build-and-lint:
    jobs:
      - build-and-lint