version: 2.1

jobs:

  test_and_lint:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: create venv
          command: make setup
      - run:
          name: install
          command: |
            make install
            ls
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test


  install-dependencies:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          name: create venv
          command: make setup
      - run:
          name: install
          command: |
            make install
            cd venv
            ls 
      - save_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  lint-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test

  build-image:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag dockey-python:$TAG .
          # echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          # docker push CircleCI-Public/circleci-demo-docker:$TAG
        
workflows:
  build-and-lint:
    jobs:
      # - test_and_lint
      - build-image
          # requires:
          #   - test_and_lint